server:
  port: 8510
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka,http://localhost:8501/eureka
spring:
  zipkin:
    base-url: http://localhost:8509
  sleuth:
    sampler:
      percentage: 1.0
