server:
  port: 8502
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8501/eureka/,http://localhost:8500/eureka
management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:8509
  application:
    name: client
  sleuth:
    sampler:
      percentage: 1.0
