server:
  port: 8507
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/xd03122049/springcloud-tutorial
          search-paths:
