eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka,http://localhost:8500/eureka
server:
  port: 8506
spring:
  application:
    name: zuul
zuul:
  routes:
    service-a:
      path: /service-a/**
      serviceId: client
    service-b:
      path: /service-b/**
      serviceId: ribbon-service
