eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka
server:
  port: 8506
spring:
  application:
    name: zuul
zuul:
  routes:
    service-a:
      path: /service-a/**
      serviceId: feign-service
    service-b:
      path: /service-b/**
      serviceId: ribbon-service