server:
  port: ${port:8501}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/,http://localhost:8500/eureka
  instance:
    hostname: eureka-server1

spring:
  application:
    name: eureka1
