server:
  port: 8507
spring:
  cloud:
    config:
      server:
        git:
#          uri: http://gitee.com/xd03122049/springcloud-tutorial
        native:
          search-locations: file:F:\\Javafile\\pinker-springcloud-admin\\config-repo\\
#          search-paths: config-repo
#          username: xd03122049
#          password: xd1610122618
#          default-label: master
  application:
    name: config-server
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka,http://localhost:8500/eureka
