server:
  port: 8507
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xd03122049/springcloud-tutorial
#          search-paths: config-repo
#           username: username
#          password: password
#          default-label: master
  application:
    name: config-server
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka
