server:
  port: 8511
spring:
  application:
    name: service-turbine
security:
  basic:
    enabled: false
turbine:
  cluster-name-expression: new String("default")
  app-config: client,client1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/,http://localhost:8501/eureka/
